### ISSUE TITLE
select roles 

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework6G3#1]
Hi team, 

Let's select our roles on the following basis:
-  maintainer: ? 
-  task 1: ?
-  task 2: ?
-  task 3: ?

**Comment by reshnashrestha** [comment]
Yeah sure let’s decide

**Comment by Pranjal-Srivastava-2023** [comment]
@reshnashrestha @s4il3sh I will be doing task 1.

**Comment by reshnashrestha** [comment]
Okay… I will be doing task 3

**Comment by reshnashrestha** [comment]
@s4il3sh are you fine with task 2 or we can switch? Let me know.

**Comment by poojashresthacode** [comment]
@Pranjal-Srivastava-2023, Have you started task 1? I have some concern.

**Comment by s4il3sh** [comment]
> @s4il3sh are you fine with task 2 or we can switch? Let me know.

Yes. I am good. We are good to go.

**Comment by reshnashrestha** [comment]
Okay keep updating
