### ISSUE TITLE
HW 6 documentation

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G3#10]
So the task assignment does not include the documentation part. Do we have to do that? If yes, Whose role could be it?
@laserlab @Pranjal-Srivastava-2023 @s4il3sh

**Comment by laserlab** [comment]
The results should be described in each individual task. Task 3 has the additional documentation task of comparing it to numpy

**Comment by reshnashrestha** [comment]
Oh that means under each task we have to create task wise documentation?

**Comment by Mosaddeq107** [comment]
@laserlab Thank you for your explanation, dear professor.
