### ISSUE TITLE
Group Number for task 1

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G3#13]
Hi all,
Have you checked on the task 1 of homework 6. It says group number in the range of interval. Are we supposed to use our homework group number or some other number there?

**Comment by reshnashrestha** [comment]
That is a bit confusing. But I don't think that is homework group number. @Pranjal-Srivastava-2023 is doing task 1. Maybe he knows something.

**Comment by WildJimmy** [comment]
I think it is the homework group number as well, I had this same issue on my project https://github.com/ubsuny/23-Homework6G1/issues/11

**Comment by reshnashrestha** [comment]
Yes, This is our homework group number.
