### ISSUE TITLE
]0, pi.group number]

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G3#20]
]: The right square bracket ] indicates that the right endpoint is included in the interval.

0: This is the lower limit of the interval.

, (comma): The comma separates the lower and upper limits of the interval.

π * GroupNumber: This expression represents the upper limit of the interval. It is the product of the mathematical constant π (pi) and a variable or constant named GroupNumber.

]: The closing square bracket ] indicates that the upper limit is included in the interval.

Putting it together, ]0, π * GroupNumber] represents a right-open interval from 0 to π * GroupNumber. It includes all real numbers greater than 0 and less than or equal to π * GroupNumber. The lower bound is closed (included), and the upper bound is open (excluded).

For example, if GroupNumber is 2, the interval becomes ]0, 2π], including 0 but excluding 2π. If GroupNumber is 3, the interval becomes ]0, 3π], and so on.

**Am I correrct?** @Pranjal-Srivastava-2023 @s4il3sh

**Comment by tirthbha** [comment]
@reshnashrestha How could we be sure particularly for this interval, do you any any explanation on this?

**Comment by reshnashrestha** [comment]
I searched for this and find similar explanation on that.
