### ISSUE TITLE
Do we need to keep the library file in a folder?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework6G3#23]
Online sources (such as https://packaging.python.org/en/latest/tutorials/packaging-projects/) tell me that when creating a python library, you need to create a folder with the python files you wish to include and an __init__.py file. However, for a single file this leads to the slightly redundant behavior I noted in this issue https://github.com/ubsuny/23-Homework6G1/issues/17.

My point is, do we need to do the whole folder setup, or are we able to just use a single file in this case?

**Comment by reshnashrestha** [comment]
I don't think it is the necessity but if you want to you can.

**Comment by reshnashrestha** [comment]
What did you choose to do @WildJimmy
