### ISSUE TITLE
Numpy integration

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G3#28]
What are they?

**Comment by Mosaddeq107** [comment]
I don't know :(

**Comment by reshnashrestha** [comment]
Which functions to consider as numpy integration?

**Comment by Pranjal-Srivastava-2023** [comment]
You can choose work done which is basically line integration.

**Comment by reshnashrestha** [comment]
@Mosaddeq107 I have completed you can check it in the main repo.
