### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G3#32]
@reshnashrestha Could you please explain that why you have added functions like root_print_header, def root_print_step,  root_max_steps, root_simple, root_secant, root_tangent in the calculus.py file?

**Comment by reshnashrestha** [comment]
As we have to generate a library named calculus.py that contains all the functions needed for task 1 and task two, I did so. You can see that in our homework before division of work.

**Comment by tirthbha** [comment]
@reshnashrestha I mean we should make different module for the root finding approach, especially for task 2.

**Comment by tirthbha** [comment]
@reshnashrestha I got it now. Thank you for your clarification.

**Comment by reshnashrestha** [comment]
No worries.
