### ISSUE TITLE
Root finding

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G3#33]
Which algorithms have you used to find roots? Can we use Bisection and Newton-Raphson method to find roots?

**Comment by reshnashrestha** [comment]
You can find the appropriate functions in the ubsuny comphys.

**Comment by tirthbha** [comment]
@reshnashrestha I know that there are already root finding tools in the CompPhys, but my question is can  we different approaches to find roots, like bisection as discussed in the class. Infact, I got know now the Newton-Raphson Method is nothing but root_tangent function defined in the rootfinding.py

**Comment by reshnashrestha** [comment]
Oh yes I have stated that in my doctoring under the calculus.py     And I think that as long as the code works, and is efficient, it’s always a good idea to find and implement new approaches.

**Comment by s4il3sh** [comment]
> Which algorithms have you used to find roots? Can we use Bisection and Newton-Raphson method to find roots?

I think we can use anyone of our choice.

**Comment by reshnashrestha** [comment]
Yes I agree.
