### ISSUE TITLE
How to compare the accuracy for task 1?

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G3#36]
In task 1 it is said to compare the accuracies (how many digits are correct) and efficiencies (how many steps does it take to reach a given accuracy). How are we supposed to take the accuracy value. Should we take adaptive trapezoid method as reference or any approximate value of true integral to compare the accuracy?

**Comment by reshnashrestha** [comment]
@Pranjal-Srivastava-2023 is doing task 1, maybe he has some ideas.

**Comment by Pranjal-Srivastava-2023** [comment]
@pratibha77118 I guess accuracy is just the number of steps it takes for each function to arrive at an acceptable answer.
