### ISSUE TITLE
Generating calculus.py

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G3#37]
Hi folks, 
Do we need to include all the functions from Task 1 and Task 2 in **calculus.py**?

**Comment by reshnashrestha** [comment]
@Mosaddeq107 Yes it is clearly mentioned in our homework task.

**Comment by s4il3sh** [comment]
> Hi folks, Do we need to include all the functions from Task 1 and Task 2 in **calculus.py**?

Yes. you have to
