### ISSUE TITLE
do we need to use boundary in task 2 as given in task 1?

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework6G3#40]

**Comment by Mosaddeq107** [comment]
I am confused about this matter as well. If you get the answer, please let me know.

**Comment by reshnashrestha** [comment]
Yes I guess we need boundary and i think it is same as in task 1. 
You can see the work in https://github.com/ubsuny/CompPhys/blob/main/Calculus/rootfinding.ipynb

**Comment by Pranjal-Srivastava-2023** [comment]
Yes, we need to use the boundaries for task 2 as well.

**Comment by AhmedCode99** [comment]
no

**Comment by AhmedCode99** [comment]
Good luck, let me know if you need help

**Comment by s4il3sh** [comment]
I have added various boundaries to it.
