### ISSUE TITLE
Task 1 Plots

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G3#41]
![plots_task1](https://github.com/ubsuny/23-Homework6G3/assets/143649367/d6f12b08-50de-41c8-9408-a7256fc78110)
Hope these graphs make sense.
In the last plot, constant=1/2, as our group number is 2.

**Comment by Mosaddeq107** [comment]
Nice output.

**Comment by uarif** [comment]
It looks correct to me, but I guess, you did not share the .py file to check the code too.

**Comment by reshnashrestha** [comment]
It looks fine. I believe that you have done nicely.

**Comment by s4il3sh** [comment]
> ![plots_task1](https://user-images.githubusercontent.com/143649367/284118362-d6f12b08-50de-41c8-9408-a7256fc78110.png) Hope these graphs make sense. In the last plot, constant=1/2, as our group number is 2.

looks great!
