### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G3#42]
I found you added a **unit testing Action** in this repository. But it can't find the **test.py** function. Are you yet to upload the **test.py** function, or is there an error in the name of the unit testing file?

**Comment by uarif** [comment]
Yes, I guess they need to add file for that

**Comment by Pranjal-Srivastava-2023** [comment]
Check our repository we have updated it.

**Comment by AhmedCode99** [comment]
Good luck, let me know if you need help
