### ISSUE TITLE
Task-3

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework6G3#49]
Hello all, I want to ask who is doing task 3 in your group. I have a question, I guess we need to check all the functions in the calculus.py or may be just two? I am a bit confused, because there are a lot of functions, right?. Thank you

**Comment by Pranjal-Srivastava-2023** [comment]
We just need any two functions.

**Comment by AhmedCode99** [comment]
two functions, your choice

**Comment by AhmedCode99** [comment]
Good luck, let me know if you need help
