### ISSUE TITLE
Commits. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework6G3#50]
I have a question, for securing the points we need to make multiple commits, so, If I fork a repository and say, make 3 commits and request for a pull so would it be counted as three commits or only one because the pull request was just one? I hope the first one is correct, otherwise there should be a lot of pull requests, right?

**Comment by s4il3sh** [comment]
> I have a question, for securing the points we need to make multiple commits, so, If I fork a repository and say, make 3 commits and request for a pull so would it be counted as three commits or only one because the pull request was just one? I hope the first one is correct, otherwise there should be a lot of pull requests, right?

Nice question. It will count as 3 commits. In the pull request, you will see 3 commits made to it.

**Comment by Pranjal-Srivastava-2023** [comment]
Yes, it will count as 3.

**Comment by uarif** [comment]
Okay, thank you

**Comment by AhmedCode99** [comment]
I think 3

**Comment by AhmedCode99** [comment]
Good luck, let me know if you need help

**Comment by Pranjal-Srivastava-2023** [comment]
Sure, we will let you know.
