### ISSUE TITLE
Resolve the merge conflict

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework6G3#52]
@reshnashrestha I have used a separate calculus.py file for importing functions to the Jupyter Notebook. I deleted the old file so you will have to resolve the conflict to merge the file.

**Comment by Pranjal-Srivastava-2023** [comment]
@reshnashrestha I just resolved the conflict so you should be able to merge.

**Comment by AhmedCode99** [comment]
The maintainer can resolve that

**Comment by AhmedCode99** [comment]
Good luck, let me know if you need help

**Comment by Pranjal-Srivastava-2023** [comment]
It is resolved now.

**Comment by reshnashrestha** [comment]
Yes and successfully merged.
