### ISSUE TITLE
task 2 tan(x) function

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework6G3#53]
How did you guys solve the issue of getting the solution for 90, 270, -90, -270, etc. degrees for the solution of tan(x) function. This solution is not right. How you are dealing with it?

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh have you figured it out?

**Comment by AhmedCode99** [comment]
Have you resolved the issue?

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh The deadline is today at 2 pm. Please let us know if you need help.

**Comment by LinxuanHu** [comment]
did you figured it out
