### ISSUE TITLE
github action.

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework6G3#54]
Does GitHub action work for you for unit test so far? @reshnashrestha

**Comment by reshnashrestha** [comment]
Yes @uarif It is working for my unit test. 
We should also lint calculus.py

**Comment by Pranjal-Srivastava-2023** [comment]
It is working for us.

**Comment by uarif** [comment]
okay, thank you

**Comment by AhmedCode99** [comment]
Good luck, let me know if you need help

**Comment by reshnashrestha** [comment]
Thank you
