### ISSUE TITLE
Merging  lead to failed github action workflows which should be managed 

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G3#55]
Hi pranjal I accepted you merge request. But the calculus.py file you created has multiple differences to the one i made. I worked on my task and had completed my task today and it took time to manage all from pylint to pytest to unit tests and all. So after merging yours, neither pytest not pylint are satisfied so now I will keep your ipynb file but I will revert to the one file I created and that calculus.py does not fall under any task so we can have our individual as per ours task in our forked repo. 
hope you are okay with it. 
![Screenshot (61)](https://github.com/ubsuny/23-Homework6G3/assets/143649458/8910fb9d-5a62-453c-b5b2-541e455a2409)

**Comment by reshnashrestha** [comment]
@Pranjal-Srivastava-2023

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework6G3/assets/143649458/8c5c99c6-073c-4304-bfcb-3151f738c55d)

**Comment by Pranjal-Srivastava-2023** [comment]
@reshnashrestha It is okay, let us keep the old file. But for my task, I modified calculus.py. I have sent you the modified version with the name calculus_main.py and the outputs are based on this.

**Comment by reshnashrestha** [comment]
Okay I will check.

**Comment by reshnashrestha** [comment]
resolved.
