### ISSUE TITLE
Asymptotes in task 2.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework6G3#59]
@s4il3sh how are you dealing with asymptotes for tan(x)?

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh The deadline is today at 2 pm. Please let us know if you need help.

**Comment by s4il3sh** [comment]
Yes. the problem is solved. Thank you for asking. For the case of asymptote i have added exception to.
