### ISSUE TITLE
Bracket]0, pi]

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework6G3#6]
]0, pi].
I have seen this type of bracket in task 1. I think this is open interval. The reason why open interval notation is not written as (0, pi) is because this notation would be ambiguous. The parentheses could be interpreted as either open interval notation or as a function call. To avoid this ambiguity, the notation ]0, pi] is used to explicitly indicate that the interval is open.

I am not sure but correct me guys if I am wrong

**Comment by reshnashrestha** [comment]
Yeah i agree.

**Comment by reshnashrestha** [comment]
]: The right square bracket ] indicates that the right endpoint is included in the interval.

0: This is the lower limit of the interval.

, (comma): The comma separates the lower and upper limits of the interval.

π * GroupNumber: This expression represents the upper limit of the interval. It is the product of the mathematical constant π (pi) and a variable or constant named GroupNumber.

]: The closing square bracket ] indicates that the upper limit is included in the interval.

Putting it together, ]0, π * GroupNumber] represents a right-open interval from 0 to π * GroupNumber. It includes all real numbers greater than 0 and less than or equal to π * GroupNumber. The lower bound is closed (included), and the upper bound is open (excluded).

For example, if GroupNumber is 2, the interval becomes ]0, 2π], including 0 but excluding 2π. If GroupNumber is 3, the interval becomes ]0, 3π], and so on.

I found this.
