### ISSUE TITLE
Methods used for task 2.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework6G3#62]
Which two methods are we using for root finding?

**Comment by AhmedCode99** [comment]
you can choose any two methods

**Comment by AhmedCode99** [comment]
Good luck, let me know if you need any help

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh The deadline is today at 2 pm.

**Comment by s4il3sh** [comment]
> Which two methods are we using for root finding?

I used all 4 methods as mentioned in calculus folder.
