### ISSUE TITLE
Task 2 updates.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework6G3#67]
Any updates @s4il3sh. Let me know if you need help.

**Comment by AhmedCode99** [comment]
Good luck, let me know if you need any help

**Comment by Pranjal-Srivastava-2023** [comment]
The deadline is today at 2:00 PM.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh The deadline is today at 2 pm. Please let us know if you need help.

**Comment by s4il3sh** [comment]
Thank you for asking @Pranjal-Srivastava-2023. It is done! I need to upload my work.

**Comment by reshnashrestha** [comment]
I just merged his work to the main.
