### ISSUE TITLE
Additional labels

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G3#8]
If you want any new labels, comment in this issue. @Pranjal-Srivastava-2023 @s4il3sh

**Comment by s4il3sh** [comment]
you may add urgent and issue fixed labels too.

**Comment by reshnashrestha** [comment]
Okay sure.

**Comment by reshnashrestha** [comment]
Are you guys needing any new labels? Let me know.

**Comment by Pranjal-Srivastava-2023** [comment]
I think there are plenty to use now, thanks!
